---
  - block: ##################################CentOS ========#
      - name: Install libselinux-python [ CentOS ]
        yum: name=libselinux-python state=present  
      - name: Install nginx for CentOS
        yum: name=nginx state=latest
      - name: Copy the nginx default [ CentOS ]
        template:
          src: default.conf
          dest: /etc/nginx/conf.d/default.conf
        become: yes
      - name: Copy the nginx-cent.conf [ CentOS ]
        template: 
          src: nginx-cent.conf
          dest: /etc/nginx/nginx.conf
        become: yes
      - name: Copying index.php file for phpinfo [ CentOS ]
        copy:
          src: index.php
          dest: /var/www/html/
        become: yes
      - name: start nginx
        service: name=nginx state=started enabled=true
    when: ansible_distribution == "CentOS"

  - block:  #========================setup for DEBIAN =======================
      - name: Install nginx [ Debian ]
        apt:
          force_apt_get: yes
          name: nginx
          state: present
      - name: Add nginx user [ Debian ]
        command: "adduser --system --no-create-home --shell /bin/false --group --disabled-login nginx"
      - name: Copy the nginx default [ Debian ]
        template:
          src: default-deb
          dest: /etc/nginx/sites-enabled/default
        become: yes
      - name: Copy the nginx.conf [ Debian ]
        template: 
          src: nginx-deb.conf
          dest: /etc/nginx/nginx.conf
        become: yes
      - name: Copying index.php file for phpinfo [ Debian ]
        copy:
          src: index.php
          dest: /var/www/html/
        become: yes
      - name: Start and enable service
        service: name=nginx state=started  enabled=true
    when: ansible_distribution == "Debian"

  - block:  #========================setup for Amazon =======================
      - name: Enable amazon-linux-extras packages [ Amazon ]
        shell: "amazon-linux-extras install nginx1 -y"
        become: yes

      - name: Start nginx [ Amazon ]
        service: name=nginx state=started enabled=true

      - name: Copy the nginx.conf [ Amazon ]
        template: 
          src: nginx-aws.conf
          dest: /etc/nginx/nginx.conf
        become: yes

      - name: Copying index.php file for phpinfo [ Amazon ]
        copy:
          src: index.php
          dest: /var/www/html/
        become: yes
    when: ansible_distribution == "Amazon"
