---
  - block: ##################################CentOS ========#
      - name: Install libselinux-python
        yum: name=libselinux-python state=present  
      - name: install nginx for CentOS
        yum: name=nginx state=latest

      - name: copy the nginx default for CentOS
        template:
          src: default.conf
          dest: /etc/nginx/conf.d/default.conf
        become: yes

      - name: copy the nginx-cent.conf for CentOS
        template: 
          src: nginx-cent.conf
          dest: /etc/nginx/nginx.conf
        become: yes

      - name: copying index.php file for phpinfo
        copy:
          src: index.php
          dest: /var/www/html/
        become: yes
      - name: start nginx
        service: name=nginx state=started enabled=true
    when: ansible_distribution == "CentOS"

  - block:  #========================setup for DEBIAN =======================
      - name: Install nginx on Debian
        apt:
          force_apt_get: yes
          name: nginx
          state: present
      - name: Add nginx user
        command: "adduser --system --no-create-home --shell /bin/false --group --disabled-login nginx"
      - name: copy the nginx default for Debian
        template:
          src: default-deb
          dest: /etc/nginx/sites-enabled/default
        become: yes
#      - name: copy the nginx.conf for Debian
#        template: 
#          src: nginx-deb.conf
#          dest: /etc/nginx/nginx.conf
#        become: yes
      - name: copying index.php file for phpinfo
        copy:
          src: index.php
          dest: /var/www/html/
        become: yes
      - name: Start and enable service
        service: name=nginx state=started  enabled=true
    when: ansible_distribution == "Debian"

  - block:  #========================setup for Amazon =======================
      - name: Enable amazon-linux-extras packages
        shell: "amazon-linux-extras install nginx1 -y"
        become: yes

      - name: start nginx 
        service: name=nginx state=started enabled=true

      - name: copy the nginx.conf for Amazon
        template: 
          src: nginx-aws.conf
          dest: /etc/nginx/nginx.conf
        become: yes

      - name: copying index.php file for phpinfo
        copy:
          src: index.php
          dest: /var/www/html/
        become: yes
    when: ansible_distribution == "Amazon"
